%Script to fit the Mixed Meal Model to measured meal challenge test data.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% load data
load('sample_data.mat')
%the data should have the following structure.
%input_data.glucose    - measured time series of plasma glucose during meal(mmol/l).
%input_data.insulin    - measured time series of plasma insulin during meal (uIU/ml).
%input_data.TG         - measured time series of plasma triglyceride during meal(mmol/l).
%input_data.NEFA       - measured time series of plasma NEFA during meal (mmol/l).
%input_data.BW         - body weight (kg).
%input_data.meal.G     - mass of glucose in the meal (mg).
%input_data.meal.TG    - mass of lipid/triglyceride in the meal (mg).
%input_data.time_G     - time points/sampling schedule for glucose measurements (mins).
%input_data.time_I     - time points/sampling schedule for insulin measurements (mins).
%input_data.time_TG    - time points/sampling schedule for triglyceride measurements (mins).
%input_data.time_NEFA  - time points/sampling schedule for NEFA measurements (mins).

%% fit model to measured data using lsqnonlin using multiple initial values;
%for addtional infomation about specific functions using to simulated or
%fit the Mixed Meal Model please look at the descriptions and comments for
%each function. 

%specify how many initial parameter sets are used.
num_par_sets = 25; 
%perform the fitting
fitting = Fit_M3al_Model_LatinHyperCube(num_par_sets,sample_data); 

%% To visualise the model fits - Multiple Initial Values

%specify plotting time
time = 0:1:480; 
%generate visualisation of multiple fits generated by Latin-HyperCube sampling
Plot_MultiFit_M3al_Model(fitting,sample_data,time); 

%% To visualise the model simulation for a specified parameter set.

% specify an individual optimatl parameter set (from fitting)
p_opt = [0.0105,0.0424,2.2975,0.00045,0.0385,0.0713,208.88,0.0163,0.0119];

%specify colour for plotting
plot_colour = [0, 0.4470, 0.7410];

figure()
% generate visualisation of model simulation for parameters p_opt. 
Plot_M3al_Model(sample_data,p_opt,time,plot_colour);
